### ISSUE TITLE
Can I program ggplot2 by observable?

### ISSUE THREAD

**Issue by BBSQQ** [observablehq/runtime#150]

**Comment by jashkenas** [comment]
I'm afraid you can't (easily). ggplot2 is an R package, and Observable is a JavaScript environment. 

You may want to check out [Vega Lite](https://vega.github.io/vega-lite/), which is a high level grammar of graphics that works well with Observable notebooks.

In the future, please ask questions in [the Observable forum](https://talk.observablehq.com), instead of opening a ticket on GitHub.
