### ISSUE TITLE
GPU.js unable to be used because require doesn't exist inside module

### ISSUE THREAD

**Issue by robertleeplummerjr** [observablehq/runtime#171]
When I add this to a notebook cell:
```js
GPU = require("gpu.js@2.0.0-rc.17/src/browser.js").catch((e) => e);
```

It fails with:
```
GPU = dt: invalid module
    at HTMLScriptElement.r.onload (https://static.observableusercontent.com/worker/worker.731df38bc78c5200f5b38b6c25e9bb975fbf691e179c435ed1a2da8a5a9f7430.js:2:39925)
```

When I debug, inside the worker which loads the library, require doesn't exist, though it exists outside in the context of the notebook's cell.

Can this be resolved?

**Comment by tmcw** [comment]
Hey Robert,

This browser.js file is a CommonJS entry point: it works when processed with browserify, but won't work with any browser or loader (Observable uses d3-require), because they don't support CommonJS (because CommonJS is synchronous, amongst other reasons).

GPU.js _does_ build browser-compatible distributions, in its `./bin/`  directory, but doesn’t include them in the NPM package and doesn’t make them UMD (browserify’s 'standalone mode'). I've opened a PR on the project - https://github.com/gpujs/gpu.js/pull/486 - which implements these changes.

**Comment by mbostock** [comment]
If you have further questions, please head over to our forum to ask for help!

https://talk.observablehq.com

**Comment by robertleeplummerjr** [comment]
Ty for helping with this, it has been resolved.
