### ISSUE TITLE
Tests fail in Node v12

### ISSUE THREAD

**Issue by visnup** [observablehq/runtime#204]
When running against Node v12 using GitHub Actions (#203), noticed that [tests fail in v12](https://github.com/observablehq/runtime/runs/261408128). Verified locally using Docker node:12-alpine.

**Comment by mbostock** [comment]
Yeah, the semantics of exactly when variables get computed are a bit messy. In Node, we use setImmediate instead of requestAnimationFrame.

https://github.com/observablehq/runtime/blob/9f9256907458b741ed6469e708897a4917b72874/src/runtime.js#L9

I wonder if we could override the definition of requestAnimationFrame in the test harness and then invoke it explicitly so that we can control exactly when variables will be computed, rather than the current `await new Promise(setImmediate)` hack.

**Comment by visnup** [comment]
Fixed in #205
