### ISSUE TITLE
parentNode or ParentElement loss in Inspector

### ISSUE THREAD

**Issue by Srabutdotcom** [observablehq/runtime#260]
I tried using define and redefined variable using standard Inspector,. but the ParentNode or ParentElement are loss in the case i want to redefine the existing variable using Inspector.into.

I suspect there is something wrong with code below.

`return new Inspector(container.appendChild(document.createElement("div")));`  in line 57 of index.js 

I mean when i create new variable and append it to observer, it is successfull showed on the html element but not when i update it using redefine variable. Please be noted that i create the container dynamically not static.

Any advice

**Comment by mbostock** [comment]
Hi @Srabutdotcom. Sorry for the delayed response here. We recommend posting to talk.observablehq.com to ask for help as you’re more likely to receive a response. If you’d still like help, can you share a link to your code running somewhere so that we can take a look? It’s hard to tell what went wrong from the description alone. Thanks.
