### ISSUE TITLE
v4.25.0 introduced breaking changes?

### ISSUE THREAD

**Issue by bplmp** [observablehq/runtime#342]
I use the runtime to embed Observable notebooks into a website. I've noticed that today these embeds stopped working. I started getting this error message: `@variable is not defined`.

When I updated my runtime package from v4.8.1 to v4.25.0 this was fixed.

**Comment by mbostock** [comment]
If you are loading that latest compiled version of notebooks from the API, you need to run the latest 4.x version of the Runtime (currently 4.25.0) alongside it. For example, if you are loading

https://api.observablehq.com/@d3/bar-chart.js?v=3

you should load the latest runtime e.g. from JsDelivr:

https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js

If you want to pin the version of the runtime, you can download your notebook as a tarball instead so that you are also pinning the compiled notebook at the same time and ensuring that it is compatible with the version of the runtime you have chosen.

Since the backwards compatibility is on the API side (rather than the Runtime), we might consider bumping the version of the compiled module (e.g., `?v=4`) to indicate that a more recent Runtime is required.

**Comment by bplmp** [comment]
Thanks for the reply and detailed explanation. I'm updating the Runtime in my package.json for now as this is simpler on my end.

**Comment by mbostock** [comment]
We’ve reverted the changes to the `?v=3` compiled format and introduced a new `?v=4` compiled format adopting dynamic imports. This should now be fixed.
