### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by yugin-pro** [observablehq/runtime#373]
Hi there!
Trying to analyse several website content using ObservableHQ Notebook
here is the code line in a cell which is perfectly working when i download something like https:site/file.json

```
{
    return fetch('https://google.com/').catch(e => e)
}
```
but when I want to parse html It return the error:

> TypeError: Failed to fetch
> at eval (observablehq-5:4:10)
> at https://static.observableusercontent.com/next/worker-d1e48427.js:2:69862
> at new Promise ()
> at ea (https://static.observableusercontent.com/next/worker-d1e48427.js:2:69830)
> at Vr.value (https://static.observableusercontent.com/next/worker-d1e48427.js:2:73824)
> at https://static.observableusercontent.com/next/worker-d1e48427.js:2:72908

**Comment by mbostock** [comment]
Please ask for help on the [Observable Forum](https://talk.observablehq.com/latest), not here.

You’ll probably want to read about [Cross-Origin Resource Sharing  (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). You might also consider [Observable Framework](https://observablehq.com/framework/) [data loaders](https://observablehq.com/framework/data-loaders) to fetch data since data loaders do not require CORS to be enabled.

**Comment by yugin-pro** [comment]
Ok I'll ask on forum, howewer here is related issue from VS code where i was recomend to create issue with Runtime
https://github.com/GordonSmith/vscode-ojs/issues/64

**Comment by mbostock** [comment]
If you’re using vscode-ojs, you’re probably better off going back over there to help. We can only help you with Observable Notebooks, which run only on observablehq.com not in VS Code. If you want something that works for local development, I recommend [Observable Framework](https://observablehq.com/framework/).
